# Generated by Django 3.2.25 on 2026-01-22 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HANYO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE1', models.CharField(max_length=20)),
                ('CODE2', models.CharField(max_length=20)),
                ('CNAME', models.CharField(max_length=60)),
                ('NAME', models.CharField(max_length=60)),
                ('STARTDATE', models.DateField(default=django.utils.timezone.now)),
                ('ENDDATE', models.DateField(default='2099-12-31')),
                ('CONTROLTEXT1', models.CharField(blank=True, max_length=50, null=True)),
                ('CONTROLTEXT2', models.CharField(blank=True, max_length=50, null=True)),
                ('CONTROLINT1', models.IntegerField(blank=True, default=0, null=True)),
                ('CONTROLINT2', models.IntegerField(blank=True, default=0, null=True)),
                ('AUTHORITY', models.CharField(max_length=20)),
                ('CREATEUSER', models.CharField(max_length=20)),
                ('CREATEDATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATEUSER', models.CharField(max_length=20)),
                ('UPDATEDATE', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KARTE_FILE',
            fields=[
                ('FILE_CODE', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FILE_NAME', models.CharField(max_length=30)),
                ('CONVERSION_FLAG', models.BooleanField(default=False)),
                ('STARTDATE', models.DateField(default=django.utils.timezone.now)),
                ('ENDDATE', models.DateField(default='2099-12-31')),
                ('CREATEUSER', models.CharField(max_length=20)),
                ('CREATEDATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATEUSER', models.CharField(max_length=20)),
                ('UPDATEDATE', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KARTE_FILE_COLUMN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FILE_CODE', models.CharField(max_length=10)),
                ('COLUMN_NAME', models.CharField(max_length=50)),
                ('BEFORE_COLUMN_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('DATA_TYPE', models.CharField(max_length=10)),
                ('ADD_COLUMN_FLAG', models.BooleanField()),
                ('ADD_COLUMN_TEXT', models.CharField(blank=True, max_length=50, null=True)),
                ('STARTDATE', models.DateField(default=django.utils.timezone.now)),
                ('ENDDATE', models.DateField(default='2099-12-31')),
                ('CREATEUSER', models.CharField(max_length=20)),
                ('CREATEDATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATEUSER', models.CharField(max_length=20)),
                ('UPDATEDATE', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KENCHI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=19)),
                ('CODE2', models.CharField(blank=True, max_length=19, null=True)),
                ('NAME', models.CharField(max_length=60)),
                ('USE_FLAG', models.CharField(max_length=1)),
                ('PREDICT_PROBA', models.DecimalField(decimal_places=1, max_digits=4)),
                ('POINTS', models.DecimalField(decimal_places=3, max_digits=9)),
                ('RULE_FLAG', models.BooleanField()),
                ('STARTDATE', models.DateField(default=django.utils.timezone.now)),
                ('ENDDATE', models.DateField(default='2099-12-31')),
                ('NOTE', models.CharField(blank=True, max_length=100, null=True)),
                ('SPARE', models.CharField(blank=True, max_length=200, null=True)),
                ('CREATEUSER', models.CharField(max_length=20)),
                ('CREATEDATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATEUSER', models.CharField(max_length=20)),
                ('UPDATEDATE', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MOVEMENT_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT_ID', models.CharField(max_length=10)),
                ('MOVE_DATETIME', models.DateTimeField(default=django.utils.timezone.now)),
                ('MOVE_CATEGORY', models.CharField(max_length=10)),
                ('WARD', models.CharField(blank=True, max_length=10, null=True)),
                ('DEPT', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RESULT_COLUMN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COLUMN_NAME', models.CharField(max_length=50)),
                ('ORIGINAL_NAME', models.CharField(max_length=50)),
                ('CREATEUSER', models.CharField(max_length=20)),
                ('CREATEDATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATEUSER', models.CharField(max_length=20)),
                ('UPDATEDATE', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USERLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=30)),
                ('STARTDATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('ENDDATE', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('STATUS_FLAG', models.CharField(max_length=1)),
                ('COMMENT', models.CharField(max_length=50)),
            ],
        ),
    ]
